import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";
import Nav from "@/components/Nav";
import Search from "@/components/Search";
import { Box, ThemeProvider } from "@mui/material";
import theme from "@/styles/theme";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Entertainment Web App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider theme={theme}>
          <Box
            display={"flex"}
            margin={"1rem"}
            justifyContent={"space-between"}
          >
            <Nav />
            <Box>
              <Search />
              {children}
            </Box>
          </Box>
        </ThemeProvider>
      </body>
    </html>
  );
}
